---
stages:
  - cleanup
  - build
  - deploy
cleanup:
  stage: cleanup
  script:
    # Stop and remove any containers with names starting with 'scaler-w1-'
    - docker ps -a | grep 'scaler-w1-' | awk '{print $1}' | xargs -r docker stop
    - docker ps -a | grep 'scaler-w1-' | awk '{print $1}' | xargs -r docker rm

    # Remove images with names starting with 'scaler' or 'openstack-exporter'
    - docker images | grep 'scaler' | awk '{print $3}' | xargs -r docker rmi
    - docker images | grep 'openstack-exporter' | awk '{print $3}' | xargs -r docker rmi

scaler_build:
  stage: build
  script:
    - echo "Stage build, Dockerfile:"
    - cd apps/OpenStack
    - cat Dockerfile
    - docker build -t scaler:$CI_PIPELINE_ID .
openstack_exporter_build:
  stage: build
  script:
    - echo "Stage build, Dockerfile:"
    - cd apps/OpenStack
    - cat Dockerfile
    - docker build -t openstack-exporter:$CI_PIPELINE_ID .
container_deploy1:
  stage: deploy
  script:
    - docker run -d -p 7474:7474 --restart=unless-stopped -e OS_AUTH_URL="$OS_AUTH_URL" -e OS_PROJECT_NAME="$OS_PROJECT_NAME" -e OS_USERNAME="$OS_USERNAME" -e OS_PASSWORD="$OS_PASSWORD" --name scaler-w1-$CI_PIPELINE_ID scaler:$CI_PIPELINE_ID



openstack_exporter_deploy:
  stage: deploy
  script:
    - docker images | grep openstack-exporter
    - docker run -d -p 5000:5000 --restart=unless-stopped -e OS_AUTH_URL=$OS_AUTH_URL -e OS_PROJECT_NAME=$OS_PROJECT_NAME -e OS_USERNAME=$OS_USERNAME -e OS_PASSWORD="$OS_PASSWORD" --name openstack-exporter-$CI_PIPELINE_ID openstack-exporter:$CI_PIPELINE_ID
    - docker ps





